"""empty message

Revision ID: 8023a32a620d
Revises: ea0c88857968
Create Date: 2020-08-01 21:52:34.322036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8023a32a620d'
down_revision = 'ea0c88857968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboutme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.BLOB(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'article', 'article_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_table('aboutme')
    # ### end Alembic commands ###
